version: '3'

services:

  node-2:
    image: "mukeunkim/agora:latest"
    ports:
      - "2826:2826"
      - "2827:2827"
    volumes:
      - "./agora/node/2/:/agora/"

  node-3:
    image: "mukeunkim/agora:latest"
    ports:
      - "3826:3826"
      - "3827:3827"
    volumes:
      - "./agora/node/3/:/agora/"

  node-4:
    image: "mukeunkim/agora:latest"
    ports:
      - "4826:4826"
      - "4827:4827"
    volumes:
      - "./agora/node/4/:/agora/"

  node-5:
    image: "mukeunkim/agora:latest"
    ports:
      - "5826:5826"
      - "5827:5827"
    volumes:
      - "./agora/node/5/:/agora/"

  node-6:
    image: "mukeunkim/agora:latest"
    ports:
      - "6826:6826"
      - "6827:6827"
    volumes:
      - "./agora/node/6/:/agora/"

  node-7:
    image: "mukeunkim/agora:latest"
    ports:
      - "7826:7826"
      - "7827:7827"
    volumes:
      - "./agora/node/7/:/agora/"

  mysql:
    image: "mysql:8.0"
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./stoa/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"

  stoa:
    image: "mukeunkim/stoa:latest"
    depends_on:
      - "node-2"
      - "node-3"
      - "node-4"
      - "node-5"
      - "node-6"
      - "node-7"
      - "mysql"
    ports:
      - "3836:3836"
    volumes:
      - "./stoa/:/stoa/wd/"

  toolsdev:
    image: "mukeunkim/toolsdev:latest"
    depends_on:
      - "node-2"
      - "node-3"
      - "node-4"
      - "node-5"
      - "node-6"
      - "node-7"
    ports:
      - "5000:5000"
    volumes:
      - "./toolsdev/:/toolsdev/wd/"
