################################################################################
##                             Network interface                              ##
################################################################################
node:
  # Run using test GenesisBlock and should use test addresses
  testing: true
  min_listeners: 6
  max_listeners: 10
  retry_delay:
    seconds: 3
  max_retries: 50
  timeout:
    seconds: 5
  # Path to the data directory (if the path doesn't exist it will be created)
  data_dir: .cache
  block_catchup_interval:
    seconds: 5
  relay_tx_max_num : 0
  relay_tx_interval:
    seconds: 0
  relay_tx_min_fee : 0
  relay_tx_cache_exp:
    seconds: 1200

interfaces:
  - type: http
    address: 0.0.0.0
    port:    2826
  - type: http
    address: 0.0.0.0
    port:    2735

admin:
  enabled: true      # `false` by default
  tls: false         # Use local tls context - `true` by default
  address: 0.0.0.0   # Private
  port: 2827         # 0xB0B
  username: admin
  pwd: s3cr3t

consensus:
  block_interval:
    seconds: 5
  validator_cycle: 20

################################################################################
##                             Validator configuration                        ##
## The server can operate in two modes: full node and validator node.         ##
## The full node does not participate in consensus,                           ##
## it only replicates the state of the blockchain.                            ##
################################################################################
validator:
  # Whether or not we should act as a validator
  # When validating, the `seed` of an eligible account is required
  # An eligible account has at least 40k coins frozen in it
  enabled: true
  # This is a randomly generated keypair
  # If this node is not a validator, this will be ignored
  #
  # DO NOT USE THOSE VALUES ANYWHERE
  # Public address:  boa1xzval2a3cdxv28n6slr62wlczslk3juvk7cu05qt3z55ty2rlfqfc6egsh2
  seed: SAQXRDHTWME4GUIVNYCKPN433VJ4BJP2L2T7UWHGSSW47VFC67EQFY3S
  # Address of the name registry
  registry_address: disabled

################################################################################
##                               Node discovery                               ##
##                                                                            ##
## When the network first starts, we need to connect to some peers to learn   ##
## the topology and find a safe intersection to listen to, and, if we are     ##
## a validator, to insert ourselves.                                          ##
################################################################################
network:
  # Supported value: IPv4, IPv6
  - http://node-3:3735
  - http://node-4:4735
  - http://node-5:5735
  - http://node-6:6735
  - http://node-7:7735

event_handlers:
  # URLs to push a data when a block is externalized. (path is "/block_externalized")
  BlockExternalized:
    addresses:
      - http://stoa:3836/block_externalized
  # URLs to push a data when a block header is updated. (path is "/block_header_updated")
  BlockHeaderUpdated:
    addresses:
      - http://stoa:3836/block_header_updated
  # URLs to push a data when a pre-image is updated. (path is "/preimage_received")
  PreimageReceived:
    addresses:
      - http://stoa:3836/preimage_received
  # URLs to push a data when a transaction is updated. (path is "/transaction_received")
  TransactionReceived:
    addresses:
      - http://stoa:3836/transaction_received
